/**
 * Generates db/fixtures/ratings.sql -- the board data the API test suite reads.
 *
 *   npx tsx src/buildRatingsFixture.ts        (from backend/ingestion)
 *
 * The rating tables are DERIVED, so they are computed from the committed sample
 * fixture rather than carved out of a dump: ratings lifted from the live
 * database would reference players and teams the sample slice does not contain.
 *
 * Rerun after anything that changes what a rating is -- a weight, a window, or
 * PLAYER_RATING_METHOD_VERSION -- or the API suite asserts against a board the
 * current model would not produce.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { startPgliteServer } from '../../pgliteTestServer.mjs';
import { computeAllPlayerRatingWindows, computeInternationalPlayerRatings } from './computePlayerRatings.js';
import { computeRatings } from './computeRatings.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const OUT = join(REPO_ROOT, 'db', 'fixtures', 'ratings.sql');

const TABLES = ['player_ratings_history', 'team_ratings_history', 'league_ratings_history'];

function literal(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return `'${value.toISOString()}'`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main() {
  const server = await startPgliteServer({ withRatings: false });
  const pool = new pg.Pool({ connectionString: server.url, max: 4 });

  console.log('computing regional windows...');
  console.log('  rows:', await computeAllPlayerRatingWindows(pool));
  console.log('computing international...');
  console.log('  rows:', await computeInternationalPlayerRatings(pool));
  console.log('computing team/league ratings...');
  await computeRatings(pool);

  let sql = `-- Generated by backend/ingestion/src/buildRatingsFixture.ts -- do not edit by hand.
-- Board data derived from db/fixtures/sample.sql by the real rating pipeline.

`;

  for (const table of TABLES) {
    const { rows, fields } = await pool.query(`SELECT * FROM ${table} ORDER BY id`);
    if (rows.length === 0) {
      console.warn(`WARNING: ${table} is empty`);
      continue;
    }
    const columns = fields.map((f) => f.name);
    const values = rows
      .map((row) => `  (${columns.map((c) => literal(row[c])).join(', ')})`)
      .join(',\n');
    sql += `INSERT INTO ${table} (${columns.join(', ')}) VALUES\n${values};\n\n`;
    console.log(`  ${String(rows.length).padStart(6)}  ${table}`);
  }

  sql += '-- Explicit ids leave every sequence at 1.\n';
  for (const table of TABLES) {
    sql += `SELECT setval('${table}_id_seq', (SELECT COALESCE(max(id), 1) FROM ${table}));\n`;
  }

  writeFileSync(OUT, sql);
  console.log(`wrote ${OUT} (${(Buffer.byteLength(sql) / 1024).toFixed(0)} KB)`);

  await pool.end();
  await server.stop();
}

await main();
