/**
 * Downloads champion portraits from Data Dragon and regenerates the name -> key
 * map the boards resolve thumbnails through.
 *
 * Riot's CDN does not refuse hotlinks the way Liquipedia does, but its URLs pin
 * a patch version that goes stale, so the art is taken once and served from our
 * own origin. Source portraits are 128px PNG (~31KB, 5.4MB for the set, as large
 * as the whole site export); stored at 64px WebP the set is ~370KB, and 64
 * rather than 48 because the board draws these near 32px and DPR 2 is common.
 *
 * The map exists because Liquipedia's display names are not Data Dragon keys and
 * the difference is not mechanical: Cho'Gath/Chogath and K'Sante/KSante drop
 * punctuation, but Wukong is MonkeyKing, Nunu & Willump is Nunu, Renata Glasc is
 * Renata. It is generated from `champion.json`, never hand-written.
 *
 *   npx tsx src/fetchChampionAssets.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const ICON_DIR = join(REPO_ROOT, 'frontend', 'public', 'champions');
const MAP_FILE = join(REPO_ROOT, 'backend', 'shared', 'src', 'championAssets.ts');
const STORED_EDGE_PX = 64;

interface ChampionEntry {
  id: string; // the asset key, e.g. "Chogath"
  name: string; // the display name, e.g. "Cho'Gath"
}

async function main(): Promise<void> {
  const versions = (await (await fetch('https://ddragon.leagueoflegends.com/api/versions.json')).json()) as string[];
  const version = versions[0];
  const champions = (await (
    await fetch(`https://ddragon.leagueoflegends.com/cdn/${version}/data/en_US/champion.json`)
  ).json()) as { data: Record<string, ChampionEntry> };

  const entries = Object.values(champions.data).sort((a, b) => a.name.localeCompare(b.name));
  console.log(`Data Dragon ${version}: ${entries.length} champions`);

  mkdirSync(ICON_DIR, { recursive: true });
  let written = 0;
  let bytes = 0;
  for (const champion of entries) {
    const response = await fetch(`https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${champion.id}.png`);
    if (!response.ok) {
      console.warn(`  ${champion.name} (${champion.id}): HTTP ${response.status}, skipped`);
      continue;
    }
    const webp = await sharp(Buffer.from(await response.arrayBuffer()))
      .resize(STORED_EDGE_PX, STORED_EDGE_PX)
      .webp({ quality: 90 })
      .toBuffer();
    writeFileSync(join(ICON_DIR, `${champion.id}.webp`), webp);
    written += 1;
    bytes += webp.byteLength;
  }
  console.log(`${written} portraits, ${Math.round(bytes / 1024)}KB total -> ${ICON_DIR}`);

  const rows = entries.map((c) => `  ${JSON.stringify(c.name)}: ${JSON.stringify(c.id)},`).join('\n');
  writeFileSync(
    MAP_FILE,
    `// GENERATED by backend/ingestion/src/fetchChampionAssets.ts from Data Dragon\n` +
      `// ${version}. Do not edit by hand; re-run that script when a champion ships.\n` +
      `const CHAMPION_ASSET_KEYS: Record<string, string> = {\n${rows}\n};\n\n` +
      `/**\n` +
      ` * Data Dragon's asset key for a Liquipedia display name, or null if it is not\n` +
      ` * one we hold art for -- which is how a newly released champion announces that\n` +
      ` * the portraits need re-fetching.\n` +
      ` */\n` +
      `export function championAssetKey(displayName: string): string | null {\n` +
      `  return CHAMPION_ASSET_KEYS[displayName] ?? null;\n` +
      `}\n`,
    'utf8',
  );
  console.log(`name -> key map -> ${MAP_FILE}`);
}

await main();
